/* Automatically generated by './build/bin/build-entry.js' */

import Pagination from '../packages/pagination/index.js';
import Dialog from '../packages/dialog/index.js';
import FileUpload from '../packages/file-upload/index.js';
import TableTree from '../packages/table-tree/index.js';
import RegionPicker from '../packages/region-picker/index.js';
import Icon from '../packages/icon/index.js';
import Throttle from '../packages/throttle/index.js';
import Debounce from '../packages/debounce/index.js';
import CollapseTransition from 'ycloud-ui/src/transitions/collapse-transition';

const components = [
  Pagination,
  Dialog,
  FileUpload,
  TableTree,
  RegionPicker,
  Icon,
  Throttle,
  Debounce,
  CollapseTransition
];

const install = function (Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
  
  Vue.prototype.$YCLOUD = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '2.6.3',
  install,
  CollapseTransition,
  Pagination,
  Dialog,
  FileUpload,
  TableTree,
  RegionPicker,
  Icon,
  Throttle,
  Debounce
};
